---
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*/
    - staging
    - trying

cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin

go:
  - 1.12.x

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

language: go

notifications:
  email:
    on_success: never

os:
  - linux
  - osx

sudo: required
