apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: default
spec:
  containers:
  - image: gcr.io/platformer-november/kubewatch:v1
    imagePullPolicy: Always
    name: kubewatch
    volumeMounts:
    - name: config-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
